name = "QuantilePriors"
uuid = "dcce4f44-1f7d-469d-bbb1-a954f1a2788e"
authors = ["John Best <jkbest@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.5"
ApproxFun = "0.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
